# Generated by Django 3.1.5 on 2021-01-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрировался')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Был в сети')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('userType', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь'), ('driver', 'Водитель'), ('operator', 'Оператор')], default='user', max_length=20, verbose_name='Тип пользователя')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=120, unique=True, verbose_name='Тип машины')),
                ('typeDescription', models.TextField(verbose_name='Описание типа')),
            ],
            options={
                'verbose_name': 'тип машины',
                'verbose_name_plural': 'типы машин',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountAmount', models.IntegerField(default=0, verbose_name='Скидка в %')),
                ('promoCode', models.CharField(max_length=200, unique=True, verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название новости')),
                ('description', models.TextField(verbose_name='Описание новости')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка новости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('startTown', models.CharField(max_length=200, unique=True, verbose_name='Начальный насел. пункт')),
                ('endTown', models.CharField(max_length=200, unique=True, verbose_name='Конечный насел. пункт')),
            ],
            options={
                'verbose_name': 'цена',
                'verbose_name_plural': 'цены',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.CharField(max_length=120, unique=True, verbose_name='Номер авто')),
                ('color', models.CharField(choices=[('yellow', 'жёлтый'), ('green', 'зелёный'), ('red', 'красный'), ('black', 'черный'), ('white', 'белый'), ('blue', 'синий')], default='white', max_length=20, verbose_name='Цвет авто')),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('LADA', 'Lada'), ('CHEVROLET', 'Chevrolet'), ('HYUNDAI', 'Hyundai'), ('MERSEDES', 'Mersedes'), ('PEUGEOT', 'Peugeot')], default='LADA', max_length=20, verbose_name='Бренд')),
                ('releaseYear', models.DateTimeField(verbose_name='Год выпуска')),
                ('isPersonal', models.BooleanField(default=False, verbose_name='Личное авто')),
                ('carType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cartype', verbose_name='Тип авто')),
            ],
            options={
                'verbose_name': 'машина',
                'verbose_name_plural': 'машины',
            },
        ),
    ]
