# Generated by Django 3.1.5 on 2021-01-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverRaitingComments',
            new_name='DriverRaitingComment',
        ),
        migrations.RenameField(
            model_name='driverraiting',
            old_name='price',
            new_name='raiting',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthDate',
        ),
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована')], default='draft', max_length=20, verbose_name='Статус новости'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('client_waiting', 'клиент ждет машину'), ('driver_waiting', 'водитель ожидает клиента'), ('client_canceled', 'клиент отменил заказ'), ('in_progress', 'клиента отвозят'), ('completed', 'заказ выполнен')], default='client_waiting', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
