export const PROFILE_REQUEST_FETCHING = 'PROFILE_REQUEST_FETCHING'
export const PROFILE_REQUEST_SUCCESS = 'PROFILE_REQUEST_SUCCESS'
export const PROFILE_REQUEST_ERROR = 'PROFILE_REQUEST_ERROR'

export const PROFILE_UPDATE = 'PROFILE_UPDATE'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR'
